server: 
  port: 3344 
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git: #https://github.com/forverActiveBoy/microservicecloud-config.git
          uri: https://github.com/forverActiveBoy/microservicecloud-config.git #GitHub上面的git仓库名字
 

